installs and uses linter, fixes
massalabs/massa-sc-toolkit pull request #103
Opened 2023-01-18 15:11 UTC by Thykof

2023-01-19 12:50 UTC, gregLibert submitted a review, later dismissed
:man_shrugging: LGTM!

2023-01-20 09:28 UTC, peterjah approved these changes

2023-01-23 11:30 UTC, longgamma-massa requested changes

2023-01-23 11:30 UTC, longgamma-massa commented on packages/sc-deployer/README.md
> +A simple use-case is as follow:
```suggestion
A simple use-case is as follows:
```

2023-01-23 11:30 UTC, longgamma-massa commented on packages/sc-deployer/assembly/contracts/deployer.ts
> + * This function deploy and call the constructor function of the deployed smart contract.
```suggestion
 * This function deploys and calls the constructor function of the deployed smart contract.
```

2023-01-23 11:30 UTC, longgamma-massa commented on packages/sc-deployer/src/index.ts
> + * Deploys multiple smart contract.
```suggestion
 * Deploys multiple smart contracts.
```

2023-01-23 11:30 UTC, longgamma-massa commented on packages/sc-deployer/src/index.ts
> + * This function will go throw all provided smart contracts.
```suggestion
 * This function will go through all provided smart contracts.
```

2023-01-23 11:30 UTC, longgamma-massa commented on packages/sc-deployer/src/index.ts
> + * For each one, it will deploy the contract and call its constructor function with the given arguments in the same
```suggestion
 * For each one, it will deploy the contract and call its constructor function with given arguments in the same
```

2023-01-23 11:30 UTC, longgamma-massa commented on packages/sc-deployer/src/index.ts
> + * The smart contracts information are stored in operation datastore with the following structure.
```suggestion
 * The smart-contract information is stored in the operation datastore with the following structure.
```

2023-01-23 11:30 UTC, longgamma-massa commented on packages/sc-deployer/README.md
> +  // This line is important. It ensure that this function can't be called in the future.
```suggestion
  // This line is important. It ensures that this function can't be called in the future.
```

2023-01-23 11:30 UTC, longgamma-massa commented on packages/sc-deployer/README.md
> +You can write a deployment script that use massa-web3 library and this sc-deployer to create complex deployment process.
```suggestion
You can write a deployment script that uses massa-web3 library and this sc-deployer to create complex deployment process.
```

2023-01-23 13:24 UTC, longgamma-massa approved these changes

2023-01-23 13:37 UTC, merged