add the "generateHeader" function (used in "generateTSCaller")
massalabs/massa-sc-toolkit pull request #224
Opened 2023-06-22 11:02 UTC by Elli610

related to #207

2023-06-22 13:53 UTC, 0xSwapFeeder approved these changes

2023-06-22 14:01 UTC, gregLibert commented on packages/massa-proto-cli/src/ts-gen.ts
> +  content += `import { Account } from 'wallet-provider';`;
Why do you need the account ?

2023-06-23 06:50 UTC, gregLibert requested changes

2023-06-23 06:50 UTC, gregLibert commented on packages/massa-proto-cli/src/ts-gen.ts
> +  return content;
```suggestion
 return `import { ${protoFile.funcName}Helper } from "${helperRelativePath}";
export interface TransactionDetails {
  operationId: string;
}\n`;
```

2023-06-23 06:50 UTC, gregLibert commented on packages/massa-proto-cli/src/ts-gen.ts
> +function generateImports(protoFile: ProtoFile, helperRelativePath): string {
Your not only importing thing, but also exporting the interface. You should remove that part of the code in another function or update the function name if you want to do both. The second approach is messier becasue functionaly you are doing two different things

2023-06-23 07:42 UTC, gregLibert commented
@Elli610 in my commit I:
- clarify the export function name (interface is a little too vague)
- set the type of `helperRelativePath`, but maybe it's not a string
- add a description for `generateTransactionDetailsExport`
- remove new lines. Using them where they will be used will make code and tests cleaner
- remove useless variable content
- improve the documentation of the functino by explaining what we are doing from a functional point of view instead of a technical one

Can you take all that into account for the other reviews ?

2023-06-26 06:32 UTC, closed without merging