add generateArgVerification
massalabs/massa-sc-toolkit pull request #226
Opened 2023-06-22 11:09 UTC by Elli610

related to #207

2023-06-22 14:21 UTC, gregLibert requested changes

2023-06-22 14:21 UTC, gregLibert commented on packages/massa-proto-cli/src/ts-gen.ts
> +function generateArgVerification(protoFile: ProtoFile): string {
What is you function doing ?
If it generates code to check if an unsigned argument of a protobuf message are negative, you should rename it to something easier to understand.

Furthermore, please add comments.

My suggestion based on what I undestand:
```suggestion
/**
 * Generates code to check if unsigned arguments of a protobuf message are negative.
 * @param {ProtoFile} protoFile - The protofile object.
 * @return {string} The string containing code for unsigned argument checks.
 */
function generateUnsignedArgCheckCode(protoFile: ProtoFile): string {
```

2023-06-22 14:21 UTC, gregLibert commented on packages/massa-proto-cli/src/ts-gen.ts
> +      arg.type === 'fixed64'
You can simplify/clarify your code by regrouping all protobu unsigned int in an array and check that this arg.type is not in this array.

Something like:
```ts
  const unsignedPBTypes = new Set(['uint32', 'uint64', 'fixed32', 'fixed64']);
  ...
    if (unsignedPBTypes.has(arg.type)) {
```

2023-06-22 14:21 UTC, gregLibert commented on packages/massa-proto-cli/src/ts-gen.ts
> +      content += `\t}\n`;
I personaly think that one template litteral is easier to read:
```suggestion
      content +=`
  if (${arg.name} < 0) {
    throw new Error("Invalid argument: ${arg.name} cannot be negative accordind to protobuf file.");
  }`;
```

2023-06-22 15:59 UTC, gregLibert requested changes

2023-06-22 15:59 UTC, gregLibert commented on packages/massa-proto-cli/src/ts-gen.ts
> +  for (let arg of protoFile.argFields) {
```suggestion
  for (const arg of protoFile.argFields) {
```

2023-06-23 07:11 UTC, Elli610 commented on packages/massa-proto-cli/src/ts-gen.ts
> +  for (let arg of protoFile.argFields) {
fixed

2023-06-26 06:32 UTC, closed without merging