add updated versions
massalabs/massa-sc-toolkit pull request #50
Opened 2022-11-18 16:09 UTC by SebastienValla

2022-11-22 13:08 UTC, peterjah requested changes

2022-11-22 13:08 UTC, peterjah commented on commands/init/package.json
> +        "@massalabs/as-tester": "^0.0.2",
you should keep the nightly version here: "^0.0.3-dev"

2022-11-22 13:08 UTC, peterjah commented on commands/init/package.json
> +        "@massalabs/massa-as-sdk": "^1.1.1",
use nightly "^1.1.2-dev"

2022-11-22 13:08 UTC, peterjah commented on commands/init/package-lock.json
> +    "lockfileVersion": 3,
why lockfileVersion changes ?? do you use a different version of npm ??

2022-11-22 13:09 UTC, thomas-senechal requested changes

2022-11-22 16:35 UTC, Thykof commented on commands/init/README.md
> +    npm run build
you're right, let's keep it

2022-11-23 08:56 UTC, peterjah approved these changes

2022-11-23 09:18 UTC, thomas-senechal approved these changes

2022-11-23 12:36 UTC, gregLibert approved these changes
:man_shrugging: LGTM

2022-11-23 12:36 UTC, merged