Add compiler folder feature
massalabs/massa-sc-toolkit pull request #59
Opened 2022-11-30 11:35 UTC by Trottoir

Allows to compile all the contracts under : 

`assembly/contracts`

2022-11-30 16:16 UTC, peterjah commented
I understand your need, and i am sure its working, but i don't think is should be done here. Toolkit should be kept a simple as possible.
maybe this code should be put in the repository you are working on ?

2022-11-30 16:23 UTC, Trottoir commented
> I understand your need, and i am sure its working, but i don't think is should be done here. Toolkit should be kept a simple as possible. maybe this code should be put in the repository you are working on ?

I totally agree with you, we kept this in the toolkit in order to ease the demo of tomorrow.
I can see it on the massa-as-sdk for instance

2022-11-30 17:55 UTC, Trottoir commented
> > > I understand your need, and i am sure its working, but i don't think is should be done here. Toolkit should be kept a simple as possible. maybe this code should be put in the repository you are working on ?
> > 
> > 
> > I totally agree with you, we kept this in the toolkit in order to ease the demo of tomorrow. I can see it on the massa-as-sdk for instance
> 
> If its only for the toworow demo, maybe you can use a specific branch of the toolkit ?

Where do you suggest to put it ? @peterjah

2022-11-30 20:49 UTC, Trottoir commented on commands/init/compiler/compiler.ts
> +    readDir(dirToCompile, function (err: NodeJS.ErrnoException | null, files: string[]) {
This is not working uWu

2022-12-01 09:25 UTC, peterjah requested changes

2022-12-01 09:25 UTC, peterjah commented on commands/init/compiler/compiler.ts
> +    return command.substring(0, command.length - 4);
i propose:
```
    return filesOrdered
        .map((file) => `npx asc ${dirToCompile}/${file} -o build/${file.replace(".ts", ".wasm")}`)
        .join(" && ");

2022-12-01 09:31 UTC, Thykof requested changes

2022-12-01 09:31 UTC, Thykof commented on commands/init/compiler/compiler.ts
> +}
```suggestion
function orderForCompilation(files: string[]): string[] {
    return files.sort(contract => {
        return readFileSync(join(dirToCompile, contract), "utf-8").includes("fileToBase64(") ? 1 : -1
    });
}
```

2022-12-01 09:31 UTC, Thykof commented on commands/init/compiler/compiler.ts
> +function prepareCommand(filesOrdered: string[]) {
```suggestion
function prepareCommand(filesOrdered: string[]): string {
```

2022-12-01 09:31 UTC, Thykof commented on commands/init/compiler/compiler.ts
> +
```suggestion
import { join } from "path";

```

2022-12-01 09:31 UTC, Thykof commented on commands/init/compiler/compiler.ts
> +        exec(command, (error, stdout, stderr) => {
```suggestion
        exec(command, (error, _, stderr) => {
```

2022-12-01 09:34 UTC, Thykof commented on commands/init/compiler/compiler.ts
> +    return command.substring(0, command.length - 4);
and use path.join

```suggestion
    return filesOrdered
        .map((file) => `npx asc ${join(dirToCompile,file)} -o build/${file.replace(".ts", ".wasm")}`)
        .join(" && ");
```

2022-12-01 09:38 UTC, peterjah requested changes

2022-12-01 09:38 UTC, peterjah commented on commands/init/compiler/compiler.ts
> +    return fileOrdered;
i propose:
```
    return files.sort((a, b) => {
        const aContent = readFileSync(`${dirToCompile}/${a}`);
        if (!aContent.includes("fileToBase64(")) {
            return -1;
        }
        return 1;
    });

2022-12-05 08:03 UTC, Thykof approved these changes

2022-12-05 17:35 UTC, gregLibert requested changes

2022-12-05 17:35 UTC, gregLibert commented on commands/init/compiler/compiler.ts
> +        return readFileSync(join(dirToCompile, contract), "utf-8").includes("fileToBase64(") ? 1 : -1;
This magic should be documented

2022-12-05 17:35 UTC, gregLibert commented on commands/init/compiler/compiler.ts
> +                console.log(error);
Are we sure that stderr will not be needed in this case ?

2022-12-05 17:35 UTC, gregLibert commented on commands/init/compiler/compiler.ts
> +        return readFileSync(join(dirToCompile, contract), "utf-8").includes("fileToBase64(") ? 1 : -1;
And we don't use file2B64 anymore.

2022-12-05 17:35 UTC, gregLibert commented on commands/init/compiler/compiler.ts
> +            return console.log("Unable to scan directory: " + err);
```suggestion
            return console.log("Unable to read directory: " + err);
```

2022-12-06 14:06 UTC, Thykof commented on commands/init/compiler/compiler.ts
> +            return;
no

2022-12-06 14:40 UTC, Thykof commented on commands/init/compiler/compiler.ts
> +        const command = prepareCommand(filesOrdered);
I now use asc, not exec

2022-12-06 17:28 UTC, gregLibert approved these changes
:clap: code is cleaner.

2022-12-06 17:29 UTC, gregLibert commented
@peterjah waiting for your feedbacks before merging.

2022-12-06 17:52 UTC, peterjah commented
> @peterjah waiting for your feedbacks before merging.

I already expressed my point of view on this.
To summarize, i think this is a specific need and it should not be part of the toolkit.
Toolkit init is a simple projet used for smart contract builder beginning with assembly script and massa.
We should keep it as simple as possible.
Moreover i think we spend time on rewritting some code which is already present here: https://github.com/massalabs/massa-sc-utils/tree/master/src/utils

we should factorize this.

2022-12-06 19:51 UTC, peterjah commented
anyway i m not against merging it. but we have to think to factorize code, and i think deployer functions should be put elsewhere!

2022-12-06 19:51 UTC, peterjah approved these changes

2022-12-07 10:45 UTC, merged