update readme
massalabs/massa-sc-toolkit pull request #94
Opened 2023-01-10 15:46 UTC by peterjah

2023-01-10 15:50 UTC, Thykof requested changes

2023-01-10 15:50 UTC, Thykof commented on packages/sc-project-initializer/commands/init/README.md
> +To use libraries, like @massalabs/massa-as-sdk and @massalabs/as, you need to import the required function, for instance :
@massalabs/as has been deprecated, now it @massalabs/as-types.

2023-01-11 16:40 UTC, Thykof requested changes

2023-01-11 16:40 UTC, Thykof commented on packages/sc-project-initializer/commands/init/README.md
>  Test framework documentation is available here: [as-pect docs](https://as-pect.gitbook.io/as-pect)
```suggestion
The test framework documentation is available here: [as-pect docs](https://as-pect.gitbook.io/as-pect)
```

2023-01-12 10:08 UTC, longgamma-massa approved these changes

2023-01-12 11:11 UTC, Thykof approved these changes

2023-01-12 11:12 UTC, merged